// src/routes/(auth)/register/+page.svelte
<script lang="ts">
  import { Loader2, UserPlus } from "lucide-svelte";

  import { enhance } from "$app/forms";
  import { toast } from "svelte-sonner";
  import { goto, invalidateAll } from "$app/navigation";
  import { cn } from "$lib/utils";

  let busy = $state(false);
  let username = $state("");
  let email = $state("");
  let password = $state("");
  let confirm = $state("");

  let strength = $derived.by(() => {
    if (!password) return 0;
    if (password.length < 6) return 1;
    if (password.length < 10) return 2;
    return /[A-Z]/.test(password) && /\d/.test(password) ? 4 : 3;
  });

  function validate(e: Event) {
    if (password !== confirm) {
      e.preventDefault();
      toast.error("Passwords don't match");
      return false;
    }
    if (password.length < 6) {
      e.preventDefault();
      toast.error("Password must be ≥ 6 characters");
      return false;
    }
    if (username.length < 3) {
      e.preventDefault();
      toast.error("Username must be ≥ 3 characters");
      return false;
    }
    return true;
  }
</script>

<svelte:head>
  <title>Create account — NovelHive</title>
</svelte:head>

<main class="mx-auto grid min-h-[80vh] w-full max-w-md place-items-center px-4 py-10">
  <div class="w-full rounded-3xl border border-white/10 bg-card/70 p-7 shadow-elevated backdrop-blur">
    <div class="mb-6 text-center">
      <img src="/logo.ico" alt="NovelHive Logo" class="mx-auto h-12 w-12" />
      <h1 class="mt-4 font-display text-2xl font-extrabold">Join NovelHive</h1>
      <p class="mt-1 text-sm text-muted-foreground">Track stories, sync progress, drop comments.</p>
    </div>

    <form 
      method="POST" 
      class="space-y-3"
      onsubmit={validate}
      use:enhance={() => {
        busy = true;
        return async ({ result }) => {
          busy = false;
          if (result.type === 'redirect') {
            toast.success("Welcome to NovelHive");
            await invalidateAll();
            goto(result.location);
          } else if (result.type === 'failure') {
            toast.error(result.data?.error || "Registration failed");
          }
        };
      }}
    >
      <div>
        <label for="username" class="mb-1 block text-xs font-bold uppercase tracking-wider text-muted-foreground">Username</label>
        <input
          id="username" required type="text" name="username" bind:value={username} placeholder="coolreader42" class="w-full rounded-xl border border-white/10 bg-white/5 px-3.5 py-2.5 text-sm focus:border-brand/60 focus:outline-none focus:ring-2 focus:ring-brand/30" />
      </div>
      <div>
        <label for="email" class="mb-1 block text-xs font-bold uppercase tracking-wider text-muted-foreground">Email</label>
        <input
          id="email" required type="email" name="email" bind:value={email} placeholder="you@example.com" class="w-full rounded-xl border border-white/10 bg-white/5 px-3.5 py-2.5 text-sm focus:border-brand/60 focus:outline-none focus:ring-2 focus:ring-brand/30" />
      </div>
      <div>
        <label for="password" class="mb-1 block text-xs font-bold uppercase tracking-wider text-muted-foreground">Password</label>
        <input
          id="password" required type="password" name="password" bind:value={password} placeholder="••••••••" class="w-full rounded-xl border border-white/10 bg-white/5 px-3.5 py-2.5 text-sm focus:border-brand/60 focus:outline-none focus:ring-2 focus:ring-brand/30" />
      </div>
      
      {#if password}
        <div>
          <div class="h-1.5 overflow-hidden rounded-full bg-white/5">
            <div
              class={cn(
                "h-full transition-all",
                strength <= 1 ? "bg-destructive" :
                strength === 2 ? "bg-warning" :
                strength === 3 ? "bg-success" : "gradient-brand",
              )}
              style="width: {Math.min(strength * 25, 100)}%"
            ></div>
          </div>
          <div class="mt-1 text-[11px] text-muted-foreground">
            {strength <= 1 ? "Weak" : strength === 2 ? "Fair" : strength === 3 ? "Good" : "Strong"} password
          </div>
        </div>
      {/if}

      <div>
        <label class="mb-1 block text-xs font-bold uppercase tracking-wider text-muted-foreground">Confirm password</label>
        <input required type="password" bind:value={confirm} placeholder="••••••••" class="w-full rounded-xl border border-white/10 bg-white/5 px-3.5 py-2.5 text-sm focus:border-brand/60 focus:outline-none focus:ring-2 focus:ring-brand/30" />
      </div>

      <button
        disabled={busy}
        class="mt-2 inline-flex w-full items-center justify-center gap-2 rounded-xl gradient-brand py-2.5 text-sm font-bold text-white shadow-glow disabled:opacity-60"
      >
        {#if busy}
          <Loader2 class="h-4 w-4 animate-spin" />
          Creating…
        {:else}
          <UserPlus class="h-4 w-4" />
          Create account
        {/if}
      </button>
    </form>

    <p class="mt-6 text-center text-sm text-muted-foreground">
      Already have an account? <a href="/login" class="font-bold gradient-text">Sign in</a>
    </p>
  </div>
</main>

// src/app/register/page.tsx
'use client';
import { signIn } from 'next-auth/react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { api } from '@/lib/api';

export default function RegisterPage() {
  const router = useRouter();
  const [form, setForm] = useState({ username: '', email: '', password: '', confirm: '' });
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const strength = form.password.length === 0 ? 0
    : form.password.length < 6 ? 1
    : form.password.length < 10 ? 2
    : /[A-Z]/.test(form.password) && /[0-9]/.test(form.password) ? 4 : 3;

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    if (form.password !== form.confirm) { setError('Passwords do not match'); return; }
    if (form.password.length < 6) { setError('Password must be at least 6 characters'); return; }
    if (form.username.length < 3) { setError('Username must be at least 3 characters'); return; }
    setLoading(true);
    try {
      await api.register({ username: form.username, email: form.email, password: form.password });
      const result = await signIn('credentials', { email: form.email, password: form.password, redirect: false });
      if (result?.ok) { router.push('/'); router.refresh(); }
      else { setError('Registration succeeded but auto-login failed. Please sign in manually.'); }
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Registration failed');
    }
    setLoading(false);
  };

  return (
    <div className="container">
      <div className="auth-container card animate-in">
        <div className="auth-header">
          <Link href="/" className="logo" style={{ justifyContent: 'center', fontSize: '2rem', marginBottom: 16 }}>NovelHive</Link>
          <h1>Create Account</h1>
          <p>Join thousands of readers</p>
        </div>

        {error && <div className="alert alert-error">{error}</div>}

        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <label className="form-label">Username</label>
            <input className="form-input" value={form.username}
              onChange={e => setForm({ ...form, username: e.target.value })} placeholder="coolreader42" required />
          </div>
          <div className="form-group">
            <label className="form-label">Email</label>
            <input className="form-input" type="email" value={form.email}
              onChange={e => setForm({ ...form, email: e.target.value })} placeholder="you@example.com" required />
          </div>
          <div className="form-group">
            <label className="form-label">Password</label>
            <input className="form-input" type="password" value={form.password}
              onChange={e => setForm({ ...form, password: e.target.value })} placeholder="••••••••" required />
            {form.password && (
              <div className="password-strength">
                <div className="strength-bar">
                  <div className={`strength-fill strength-${strength}`} style={{ width: `${strength * 25}%` }} />
                </div>
                <span className="strength-text">
                  {strength <= 1 ? 'Weak' : strength === 2 ? 'Fair' : strength === 3 ? 'Good' : 'Strong'}
                </span>
              </div>
            )}
          </div>
          <div className="form-group">
            <label className="form-label">Confirm Password</label>
            <input className="form-input" type="password" value={form.confirm}
              onChange={e => setForm({ ...form, confirm: e.target.value })} placeholder="••••••••" required />
          </div>
          <button className="btn btn-primary btn-lg" type="submit" disabled={loading}
            style={{ width: '100%', marginTop: 8 }}>
            {loading ? 'Creating account...' : 'Create Account'}
          </button>
        </form>

        <p style={{ textAlign: 'center', marginTop: 24, color: 'var(--text-secondary)', fontSize: '0.9rem' }}>
          Already have an account?{' '}
          <Link href="/login" style={{ color: 'var(--accent)', fontWeight: 600 }}>Sign in</Link>
        </p>
      </div>
    </div>
  );
}
